config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  resources :tweets

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
	
	def index
		@tweets = Tweet.all
	end

	def show
		find_tweet
	end

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.create
		redirect_to(@tweet)
	end

	def edit
		find_tweet
	end

	def update
		find_tweet
		@tweet.update(tweet_params)
		redirect_to(@tweet)
	end

private
	def find_tweet
		@tweet = Tweet.find(params[:id])
	end

	def tweet_params
		params[:tweet]
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def index
		@tweets = Tweet.all
	end

	def show
		find_tweet
	end

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.create((tweet_params).permit(:text))
		redirect_to(@tweet)
	end

	def edit
		find_tweet
	end

	def update
		find_tweet
		@tweet.update((tweet_params).permit(:text))
		redirect_to(@tweet)
	end

private
	def find_tweet
		@tweet = Tweet.find(params[:id])
	end

	def tweet_params
		params[:tweet]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweet/edit.html.erb
<h1>Edit Tweet</h1>

<%= form_for(@blog) do |f| %>
	<p>
		<%= f.label(:text) %>
		<%= f.text_field(:text) %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/tweet/index.html.erb
<h1>All Tweets</h1>
<p><%= link_to('Create a Tweet', new_tweet_url) %></p>

<p>There are <%= @tweets.count %> tweets.</p>

<% @tweets.each do |tweets| %>
	<p>
		<%= link_to(tweet.text, tweet) %>
		<%= edit_tweet_link(tweet) %>
	</p>
<% end %>

app/views/tweet/show.html.erb
<h1>Tweet Details</h1>
<p>This is tweet #<%= @tweet.id %></p>
<p><%= @tweet.text %></p>
<p><%= edit_tweet_link(@tweet) %></p>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= form_for(@tweet) do |f| %>
	<p>
		<%= f.label(:text) %>
		<%= f.text_field(:text) %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/tweets/index.html.erb
<h1>All Tweets</h1>
<p><%= link_to('Create a Tweet', new_tweet_url) %></p>

<p>There are <%= @tweets.count %> tweets.</p>

<% @tweets.each do |tweet| %>
	<p>
		<%= link_to(tweet.text, tweet) %>
	
		<%= link_to('Edit', edit_tweet_url(tweet)) %>
	</p>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= form_for(@tweet) do |f| %>
	<p>
		<%= f.label(:text) %>
		<%= f.text_field(:text) %>
	</p>
	<p>
		<%= f.submit %>
	</P>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweet Details</h1>
<p>This is tweet #<%= @tweet.id %></p>
<p><%= @tweet.text %></p>
<p><%= link_to('Edit', edit_tweet_url(@tweet)) %></p>